### PR TITLE
Full and pilot

### PR DESCRIPTION
**Pull request by DMSaunders**

### CODE REVIEW

**Comment by DMSaunders** [comment]
This is a folder structure that we discussed at BrightHive which loses no information from master, and adds a directory which is a profile that only removes some lines from (and adds none to) full. The only conflict is `workHours.jsonld` since you just changed it. Of course, your version should prevail.

**Comment by stuartasutton** [comment]
@DMSaunders, your files to merge don't have the definition property populated (i.e., "[TBD]") all of descriptions have been added for all of the concept schemes on master.

**Comment by DMSaunders** [comment]
@stuartasutton The definition properties are populated in the concept schemes within the full directory. They are not populated in the v0.9.0 directory since that is essentially a snapshot of the pilot. However, if you'd prefer we have the definition property populated in the v0.9.0, I can make that change.

**Comment by stuartasutton** [comment]
All properties, classes, concepts, declared as part of a language of description need definitions.

**Comment by DMSaunders** [comment]
@stuartasutton Added.

**Pull request merged**
